### ISSUE TITLE
Lines between + border around DWD-Warning

### ISSUE THREAD

**Issue by Gittegatt** [jclarke0000/MMM-OpenWeatherForecast#11]
Hello @jclarke0000 ,
first of all: Thank you for that nice and clean modern designed weather module! Appreciate it! Very like it!

I have a question about the lines and the border around the DWD-Warning. You can find a screenshot at the bottom.
Is it possible to get rid of them or hide those lines? I already tried with different parameters via css in custom.css - code parameters below. Sorry for the code alignment, but I dont know how to insert line breakes here.

`.MMM-OpenWeatherForecast {
border: none;
border-style: none;
}`

`.MMM-OpenWeatherForecast table tr {
border-bottom: solid 0px #222;
border-top: solid 0px #222;
border: none;
border-style: none;
}`

![lines_and_borders](https://user-images.githubusercontent.com/47114680/140768356-cb57eeb4-edfb-41a2-9625-26ebd08d690e.png)

**Comment by kenzo94** [comment]
Hey @Gittegatt,

how did you only display one weather warning? Somehow it display both language on my mirror. 
![image](https://user-images.githubusercontent.com/39488126/140979791-34e1b2f8-121d-4d5d-90d3-4f0e96031de3.png)

**Comment by Gittegatt** [comment]
Hello @kenzo94,
I hopefully configured and tried first with parameter `language: 'de'`, second try with `lang: 'de'` cause the [API call](https://openweathermap.org/api/one-call-api#multi) requires `lang:`. Anyway, unfortunately the DWD warn window, it stayed english. Also tried without the optional language option, that I thought its getting the language setting from the general MagicMirror config section on top, but it doesnt.

Means:
```
let config = {
        ....
	language: "de",
	locale: "de",
        ....
} 
```

Maybe we can compare and merge our configs. My config below.

```
		{
			module: "MMM-OpenWeatherForecast",
			position: "top_right",
			header: "",
			config: {
			  apikey: "XXXXXXXXXXXXXXXXXXXXXXXX", //only string here
			  latitude: XX.XXXXXX,            //number works here or string
			  longitude: X.XXXXXX,
			  language: "de",
			  label_hourlyTimeFormat: "kk[]"+":"+"mm[]",	//24h format
			  label_sunriseTimeFormat: "kk[]"+":"+"mm[]",	//24h format
			  label_days: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
			  label_ordinals: ["N", "NNO", "NO", "ONO", "O", "OSO", "SO", "SSO", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"],
			  
			  showCurrentConditions: true,
			  showSummary: true,
			  showExtraCurrentConditions: true,
			  extraCurrentConditions: {
				highLowTemp: true,
				precipitation: true,
				sunrise: true,
				sunset: true,
				wind: true,
				barometricPressure: false,
				humidity: true,
				dewPoint: false,
				uvIndex: true,
				visibility: false
			  },

			  forecastLayout: "table",
			  forecastHeaderText: "",

			  hourlyForecastTableHeaderText: "",
			  showHourlyForecast: true,
			  showHourlyTableHeaderRow: true,
			  hourlyForecastInterval: 4,
			  maxHourliesToShow: 6,
			  hourlyExtras: {
				precipitation: true,
				wind: true,
				barometricPressure: false,
				humidity: false,
				dewPoint: false,
				uvIndex: false,
				visibility: false
			  },

			  dailyForecastTableHeaderText: "",
			  showDailyForecast: true,
			  showDailyTableHeaderRow: true,
			  maxDailiesToShow: 5,
			  dailyExtras: {
				precipitation: true,
				sunrise: false,
				sunset: false,
				wind: true,
				barometricPressure: false,
				humidity: false,
				dewPoint: false,
				uvIndex: false
				}
			},
		},
```

Regards.

**Comment by kenzo94** [comment]
@Gittegatt I have almost the same config, except for:

```
let config = {
        ....
	language: "de",
	locale: "de-DE",
        ....
} 

```

**Comment by Gittegatt** [comment]
@kenzo94 
Maybe an update / re-install with npm install could help.

**Comment by Gittegatt** [comment]
@kenzo94 
found this in MM forum posted by jeff, same issue. Doubled display is a problem with OpenWeather’s API.
[https://forum.magicmirror.builders/topic/14717/mmm-openweatherforecast-replacement-for-mmm-darkskyforecast/96?lang=en-US&page=10](url)
