### ISSUE TITLE
label_timeFormat not working 

### ISSUE THREAD

**Issue by kurtern84** [jclarke0000/MMM-OpenWeatherForecast#5]
Hi! 
I have this setup:

`label_timeFormat: "HH:mm",`
`label_sunriseTimeFormat: "HH:mm",`

But it's only working on label_sunriseTimeFormat.

**Comment by rabbit83ka** [comment]
Hi, you have to use `label_hourlyTimeFormat: "HH.mm"`. See #6

**Comment by jclarke0000** [comment]
README,md corrected to reflect the correct label.  @rabbit83ka is correct.  You need to use `label_hourlyTimeFormat`
