### ISSUE TITLE
Request: A configuration switch to disable weather alerts

### ISSUE THREAD

**Issue by BrianC0000** [jclarke0000/MMM-OpenWeatherForecast#7]
Thanks to all invoved in this one - I love what you've done with this module... 

I'm hoping that it may be possible to add a switch which would prevent active weather alerts from displaying in the summary area.  I want the summary, just not the alerts, as that object pushes the module's height to beyond the ideal.  I suppose I could just suppress the entire summary object, but I thought I'd ask. 

Thanks agian!
![image](https://user-images.githubusercontent.com/26088997/110843966-e2567200-8276-11eb-89d4-c9e77386f501.png)

**Comment by OberfragGER** [comment]
Ohh. Thanks a lot. i also got a weather warning in Germany but still english text.
Is it possible to change the language of the warning?

**Comment by OberfragGER** [comment]
@BrianC0000 : Your choice could be "showSummary: false,"

In my case- the warning got away.

**Comment by BrianC0000** [comment]
I know this - but I'm requesting an enhancement to be able to show the Summary with no alerts

**Comment by swvalenti194** [comment]
> I know this - but I'm requesting an enhancement to be able to show the Summary with no alerts

I am looking for the same

**Comment by Sceetch** [comment]
does anybody has a solution? is it possible to switch the warning into another language? preferd German?
Or is it possible to hide these messages?

**Comment by OberfragGER** [comment]
@Sceetch : Yes. Its possible. With custom.css.
Warnings are from the API.
See forum:
https://forum.magicmirror.builders/topic/14717/mmm-openweatherforecast-replacement-for-mmm-darkskyforecast/39

**Comment by BrianC0000** [comment]
> @Sceetch : Yes. Its possible. With custom.css.
> Warnings are from the API.
> See forum:
> https://forum.magicmirror.builders/topic/14717/mmm-openweatherforecast-replacement-for-mmm-darkskyforecast/39

YES!!  Thank you so very much!  That's the secret sauce.
