### ISSUE TITLE
Wind in kmh and winddirection

### ISSUE THREAD

**Issue by thatstheplace** [jclarke0000/MMM-OpenWeatherForecast#9]
Hey,

first of all: This module is best! Thank you for your work! Really upgrading the look and function of my mirror!

I have a few questions:

I seen you have the wind in km/h on your screenshots but I don't find any options to configure this.

Also I see we can rename the wind directions but where is the option to actual show them?

Maybe I'm blind? My language is german and units are metric, think thats the only relevant differences to the sample config which can affect these.

Hope you can help.

Greetings

**Comment by ghost** [comment]
To show the wind speed in km/h add this to your configuration `displayKmhForWind = true` and to rename the wind directions to German add this to your configuration:
`label_ordinals = ["N", "NNO", "NO", "ONO", "O", "OSO", "SO", "SSO", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"]`.

**Comment by thatstheplace** [comment]
Thanks for the solution!
